name: Dailyge-Api PR

on:
  pull_request:
    branches: [ dev ]

env:
  ENV: dev
  PROD_ECR_URI: ${{ secrets.PROD_ECR_URI }}
  DEV_ECR_URI: ${{ secrets.DEV_ECR_URI }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 with Gradle cache
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Create Test Config
        env:
          APPLICATION_TEST_CONFIG: ${{ secrets.APPLICATION_TEST_CONFIG }}
        run: |
          echo "$APPLICATION_TEST_CONFIG" > dailyge-api/src/test/resources/application-test.yml

      - name: Build with Gradle
        run: ./gradlew dailyge-api:build --info --stacktrace

      - name: Notify Build Result to Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,commit,message,author
          status: ${{ job.status }}
          text: |
            *Actor:* ${{ github.actor }}
            *Commit:* ${{ github.sha }}
            *Sonarqube:* <${{ secrets.SONAR_HOST_URL }}|정적 분석지표>
            *Repository:* <https://github.com/${{ github.repository }}|${{ github.repository }}>
          username: 'PR_Bot'
          icon_emoji: ':robot_face:'
          channel: 'pr'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PR_WEBHOOK_URL }}
