name: Dailyge-API PR

on:
  pull_request:
    branches: [ dev ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
  build:
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        env:
          ENV: ${{ secrets.ENV }}
          PROD_ECR_URI: ${{ secrets.PROD_ECR_URI }}
          DEV_ECR_URI: ${{ secrets.DEV_ECR_URI }}
        run: ./gradlew dailyge-api:build
