name: Dailyge-Api Dev CI

on:
  pull_request:
    branches: [ dev ]
    paths:
      - "dailyge-api/**"
      - ".github/workflows/**"

env:
  ENV: dev
  PROD_ECR_URI: ${{ secrets.PROD_ECR_URI }}
  DEV_ECR_URI: ${{ secrets.DEV_ECR_URI }}
  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  ENCRYPTOR_KEY: ${{ secrets.ENCRYPTOR_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}
      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-2/files-2.1
            ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17 with Gradle
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Build with Gradle Without Test
        env:
          ENCRYPTOR_KEY: ${{ secrets.ENCRYPTOR_KEY }}
        run: ./gradlew dailyge-api:build -x test --info --stacktrace
